[package]
name = "brokenblog"
version = "0.1.0"
authors = ["fred <fredlahde@gmail.com>"]

[dependencies]
serde_json = "1.0"
serde_derive = "1.0.80"
serde = "1.0.80"
rocket = "0.3.17"
rocket_codegen = "0.3.17"
lazy_static = "1.0"
chrono = "0.4.6"
